export type Airport = { code: string; name: string; city: string; country: string };

export const AIRPORTS: Airport[] = [
  // India
  { code: "AGX", name: "Agatti Airport", city: "Agatti", country: "India" },
  { code: "COK", name: "Cochin International Airport", city: "Kochi", country: "India" },
  { code: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram", country: "India" },
  { code: "CCJ", name: "Calicut International Airport", city: "Kozhikode", country: "India" },
  { code: "CNN", name: "Kannur International Airport", city: "Kannur", country: "India" },
  { code: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "India" },
  { code: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India" },
  { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India" },
  { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "India" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "India" },
  { code: "GOI", name: "Goa International Airport (Dabolim)", city: "Goa", country: "India" },
  { code: "GOX", name: "Manohar International Airport (Mopa)", city: "Goa", country: "India" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "India" },
  { code: "PNQ", name: "Pune Airport", city: "Pune", country: "India" },
  { code: "JAI", name: "Jaipur International Airport", city: "Jaipur", country: "India" },
  { code: "LKO", name: "Chaudhary Charan Singh International", city: "Lucknow", country: "India" },
  { code: "IXC", name: "Chandigarh International Airport", city: "Chandigarh", country: "India" },
  { code: "GAU", name: "Lokpriya Gopinath Bordoloi International", city: "Guwahati", country: "India" },
  { code: "PAT", name: "Jay Prakash Narayan International", city: "Patna", country: "India" },
  { code: "BBI", name: "Biju Patnaik International Airport", city: "Bhubaneswar", country: "India" },
  { code: "IXM", name: "Madurai Airport", city: "Madurai", country: "India" },
  { code: "TRZ", name: "Tiruchirappalli International Airport", city: "Tiruchirappalli", country: "India" },
  { code: "IXE", name: "Mangalore International Airport", city: "Mangalore", country: "India" },
  { code: "VTZ", name: "Visakhapatnam International Airport", city: "Visakhapatnam", country: "India" },
  { code: "NAG", name: "Dr. Babasaheb Ambedkar International", city: "Nagpur", country: "India" },
  { code: "IDR", name: "Devi Ahilya Bai Holkar Airport", city: "Indore", country: "India" },
  { code: "SXR", name: "Sheikh ul-Alam International Airport", city: "Srinagar", country: "India" },
  { code: "IXJ", name: "Jammu Airport", city: "Jammu", country: "India" },
  // Gulf
  { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
  { code: "DWC", name: "Al Maktoum International Airport", city: "Dubai", country: "UAE" },
  { code: "AUH", name: "Zayed International Airport", city: "Abu Dhabi", country: "UAE" },
  { code: "SHJ", name: "Sharjah International Airport", city: "Sharjah", country: "UAE" },
  { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { code: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait" },
  { code: "BAH", name: "Bahrain International Airport", city: "Manama", country: "Bahrain" },
  { code: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman" },
  { code: "SLL", name: "Salalah Airport", city: "Salalah", country: "Oman" },
  { code: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia" },
  { code: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia" },
  { code: "DMM", name: "King Fahd International Airport", city: "Dammam", country: "Saudi Arabia" },
  { code: "MED", name: "Prince Mohammad Bin Abdulaziz Airport", city: "Madinah", country: "Saudi Arabia" },
  // Asia
  { code: "MLE", name: "Velana International Airport", city: "Malé", country: "Maldives" },
  { code: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka" },
  { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
  { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
  { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { code: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand" },
  { code: "HKT", name: "Phuket International Airport", city: "Phuket", country: "Thailand" },
  { code: "CGK", name: "Soekarno–Hatta International Airport", city: "Jakarta", country: "Indonesia" },
  { code: "DPS", name: "Ngurah Rai International Airport", city: "Bali", country: "Indonesia" },
  { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong" },
  { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan" },
  { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
  { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
  { code: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal" },
  { code: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh" },
  // Europe
  { code: "LHR", name: "London Heathrow Airport", city: "London", country: "United Kingdom" },
  { code: "LGW", name: "London Gatwick Airport", city: "London", country: "United Kingdom" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { code: "CDG", name: "Paris Charles de Gaulle Airport", city: "Paris", country: "France" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { code: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy" },
  { code: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", city: "Madrid", country: "Spain" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  // Americas
  { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
  { code: "EWR", name: "Newark Liberty International Airport", city: "Newark", country: "USA" },
  { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
  { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
  { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
  { code: "IAD", name: "Washington Dulles International Airport", city: "Washington", country: "USA" },
  { code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
  { code: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
  // Oceania & Africa
  { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { code: "JNB", name: "O. R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
  { code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
  { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
];
