/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisasRouteImport } from './routes/visas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisasSlugRouteImport } from './routes/visas.$slug'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'

const VisasRoute = VisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisasSlugRoute = VisasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VisasRoute,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visas': typeof VisasRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/visas/$slug': typeof VisasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visas': typeof VisasRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/visas/$slug': typeof VisasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flights': typeof FlightsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visas': typeof VisasRouteWithChildren
  '/packages/$slug': typeof PackagesSlugRoute
  '/visas/$slug': typeof VisasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/flights'
    | '/packages'
    | '/sitemap.xml'
    | '/visas'
    | '/packages/$slug'
    | '/visas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/flights'
    | '/packages'
    | '/sitemap.xml'
    | '/visas'
    | '/packages/$slug'
    | '/visas/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/flights'
    | '/packages'
    | '/sitemap.xml'
    | '/visas'
    | '/packages/$slug'
    | '/visas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FlightsRoute: typeof FlightsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisasRoute: typeof VisasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visas': {
      id: '/visas'
      path: '/visas'
      fullPath: '/visas'
      preLoaderRoute: typeof VisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visas/$slug': {
      id: '/visas/$slug'
      path: '/$slug'
      fullPath: '/visas/$slug'
      preLoaderRoute: typeof VisasSlugRouteImport
      parentRoute: typeof VisasRoute
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
  }
}

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

interface VisasRouteChildren {
  VisasSlugRoute: typeof VisasSlugRoute
}

const VisasRouteChildren: VisasRouteChildren = {
  VisasSlugRoute: VisasSlugRoute,
}

const VisasRouteWithChildren = VisasRoute._addFileChildren(VisasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FlightsRoute: FlightsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisasRoute: VisasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
